# Generated by Django 3.2.13 on 2022-06-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('jenis_kelamin', models.CharField(choices=[('Laki - Laki', 'Laki - Laki'), ('Perempuan', 'Perempuan')], max_length=50, verbose_name='Jenis Kelamin')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orang')),
            ],
            options={
                'verbose_name': 'Orang',
                'verbose_name_plural': 'Orang',
            },
        ),
        migrations.RemoveField(
            model_name='replies',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
