# Generated by Django 3.2.13 on 2022-06-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220614_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.orang'),
        ),
    ]
